name: Bug report form
description: Create a bug report for the Makefile Tools extension.
title: "[Bug] "
labels:
  - "bug"
  - "triage"
body:
- type: markdown
  attributes:
    value: |
      ### Is there an existing bug report for this?
      Please search our [existing issues](https://github.com/microsoft/vscode-makefile-tools/issues) to see if an issue already exists for the bug you'd like to report.
- type: textarea
  attributes:
    label: Brief Issue Summary
    description: |
      Put a short summary here.
      Please provide clear instructions as to how we can reproduce the bug on our end.
  validations:
    required: true
- type: textarea
  attributes:
    label: Debug Log
    description: |
      We would also appreciate it if you used the `"makefile.loggingLevel": "debug"` setting and paste the Makefile tools output from the OUTPUT window.
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Optionally provide other information that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
