# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  branches:
    include:
      - refs/heads/main

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  - name: Codeql.Enabled
    value: true
  - name: Codeql.TSAEnabled
    value: true
  - name: TeamName
    value: C++ Cross Platform and Cloud

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: AzurePipelinesWindows2022compliantGPT
        os: windows
      componentgovernance:
        ignoreDirectories: node_modules,dist,i18n
        alertWarningLevel: Medium
      policheck:
        enabled: true
      tsa:
        enabled: true
        config:
          tsaVersion: TsaV2
          codebase: NewOrUpdate
          codebaseName: vscode-makefile-tools
          tsaStamp: $(Tsa.AdoProject)
          tsaEnvironment: PROD
          notificationAliases: $(Tsa.NotificationAliases)
          codebaseAdmins: $(Tsa.CodebaseAdmins)
          instanceUrl: $(Tsa.AdoOrg)
          projectName: $(Tsa.AdoProject)
          areaPath: $(Tsa.AreaPath)
          iterationPath: $(Tsa.AdoProject)
          allTools: true
          repositoryName: vscode-makefile-tools
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: stage
        jobs:
          - job: Job_1
            displayName: Agent job 1
            steps:
              - checkout: self
                fetchTags: false

              - task: NodeTool@0
                displayName: Use Node 16.x
                inputs:
                  versionSpec: 16.x

              - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
                displayName: Use Yarn 1.x

              - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
                displayName: Yarn install
                inputs:
                  arguments: install

              - task: Npm@0
                displayName: npm install vsce
                inputs:
                  arguments: -g vsce

              - task: CmdLine@2
                displayName: Run VSCE to package vsix
                inputs:
                  script: |-
                    echo Building VSIX
                    vsce package --yarn -o $(Build.StagingDirectory)\makefile-tools.vsix

              - task: Npm@0
                displayName: npm uninstall vsce
                inputs:
                  command: uninstall
                  arguments: -g vsce

              - task: DeleteFiles@1
                displayName: Remove code that should not be scanned
                inputs:
                  Contents: |-
                    node_modules
                    dist
                    i18n
